app:
  name: "app"

http:
  port: 8080

db:
  host: "postgres"
  port: "5432"
  user: "app_admin"
  password: "app_admin"
  name: "app"
  dialect: "postgres"

redis:
  host: "redis"
  port: "6379"
  password: "app_admin"