apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: app
data:
  default.conf: |
    upstream backend { server backend:8080; }
    server {
        listen 80;
        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
